theme = "plain"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
cursorline = true
rulers = [80]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.lsp]
display-messages = true

[editor.inline-diagnostics]
cursor-line = "error"

# [editor.whitespace]
# render = "all"

[editor.file-picker]
hidden = false

[keys.normal]
X = "select_line_above"
"ret" = "goto_word"

[keys.select]
X = "select_line_above"
