theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.file-picker]
hidden = false
