theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
cursorline = true
continue-comments = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.soft-wrap]
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false
