# attribute = "red"
keyword = { modifiers = ["bold"] }
# "keyword.directive" = "lilac" # -- preprocessor comments (#if in C)
namespace = "black"
# punctuation = "lavender"
# "punctuation.delimiter" = "lavender"
# operator = "lilac"
special = "blue"
# "variable.other.member" = "white"
# variable = "lavender"
# # variable = "almond" # TODO: metavariables only
# # "variable.parameter" = { fg = "lavender", modifiers = ["underlined"] }
# "variable.parameter" = { fg = "lavender" }
# "variable.builtin" = "mint"
type = "blue"
# "type.builtin" = "white" # TODO: distinguish?
# constructor = { modifiers = ["bold"] }
# function = { modifiers = ["bold"] }
# "function.macro" = "lilac"
# "function.builtin" = "white"
# tag = "almond"
comment = { modifiers = ["italic", "dim"] }
constant = "blue"
"constant.builtin" = "blue"
string = "blue"
"constant.numeric" = "blue"
"constant.character.escape" = "blue"
# # used for lifetimes
# label = "honey"
# tabstop = { modifiers = ["italic"], bg = "bossanova" }

"markup.heading" = { modifiers = ["bold"]}
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "silver", modifiers = ["underlined"] }
# "markup.link.text" = "almond"
# "markup.raw" = "almond"

# "diff.plus" = "#35bf86"
# "diff.minus" = "#f22c86"
# "diff.delta" = "#6f44f0"

# # TODO: differentiate doc comment
# # concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "white" }
# "ui.background.separator" = { fg = "blue" }
"ui.linenr" = { fg = "light-black" }
"ui.linenr.selected" = { fg = "black", modifiers = ["bold"] }
"ui.statusline" = { bg = "lightest-gray" }
"ui.statusline.inactive" = { bg = "white" }
"ui.popup" = { bg = "lightest-gray" }
"ui.window" = { bg = "white" }
# "ui.help" = { bg = "#7958DC", fg = "#171452" }
# "ui.text" = { fg = "black" }
# "ui.text.focus" = { fg = "white" }
# "ui.text.inactive" = "sirocco"
# "ui.text.directory" = { fg = "lilac" }
# "ui.virtual" = { fg = "comet" }
"ui.virtual.ruler" = { bg = "lightest-gray" }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "light-black" }

"ui.selection" = { bg = "lighter-yellow" }
# "ui.selection.primary" = { bg = "#540099" }
# # TODO: namespace ui.cursor as ui.selection.cursor?
# "ui.cursor.select" = { bg = "delta" }
# "ui.cursor.insert" = { bg = "white" }
# "ui.cursor.primary.select" = { bg = "delta" }
# "ui.cursor.primary.insert" = { bg = "white" }
"ui.cursor.match" = { modifiers = ["bold"] }
# "ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "lightest-gray" }
"ui.highlight" = { bg = "lighter-gray" }
# "ui.highlight.frameline" = { bg = "#634450" }
# "ui.debug" = { fg = "#634450" }
# "ui.debug.breakpoint" = { fg = "apricot" }
"ui.menu" = { bg = "lightest-gray" }
"ui.menu.selected" = { bg = "light-blue" }
"ui.menu.scroll" = { bg = "lighter-gray" }

"diagnostic.hint" = { bg = "white", underline = { color = "lighter-black", style = "curl" } }
"diagnostic.info" = { underline = { color = "lighter-black", style = "curl" } }
"diagnostic.warning" = { bg = "white", underline = { color = "lighter-black", style = "curl" } }
"diagnostic.error" = { underline = { color = "lighter-black", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "red"
error = "red"
info = "blue"
hint = "blue"

[palette]
black = "#222222"
light-black = "#424242"
lighter-black = "#545454"
white = "#F1F1F1"

medium_gray = "#767676"
light-gray = "#999999"
lighter-gray = "#CCCCCC"
lightest-gray = "#E5E5E5"

blue = "#008EC4"
light-blue = "#B6D6FD"

cyan = "#20A5BA"
light-cyan = "#4FB8CC"

red = "#C30771"
light-red = "#E32791"

green = "#10A778"
light-green = "#5FD7A7"

purple = "#523C79"
light-purple = "#68555DE"

yellow = "#A89C14"
light-yellow = "#F3E430"
lighter-yellow = "#FAF5B8"
